// <auto-generated />
using System;
using Bookstore.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookstore.Migrations
{
    [DbContext(typeof(BookstoreContext))]
    [Migration("20240803140132_bookstoreinitialseed")]
    partial class bookstoreinitialseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bookstore.Entities.Authors", b =>
                {
                    b.Property<int>("Author_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Author_Id"));

                    b.Property<string>("Author_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Author_Id");

                    b.HasIndex("Author_Name", "Biography")
                        .IsUnique();

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Author_Id = 1,
                            Author_Name = "Nancy Bond",
                            Biography = "Nancy Bond is a prolific fantasy writer known for her richly imagined worlds, complex characters, and epic narratives that captivate readers of all ages. Her ability to blend elements of magic and adventure has made her a favorite among fantasy enthusiasts worldwide.",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2523),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2524),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 2,
                            Author_Name = "AK Gandhi",
                            Biography = "AK Gandhi born in Meerut took retirement from the Indian Air Force in 1995 at a young age and engaged himself as full-time freelance writer and translator.",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2529),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2530),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 3,
                            Author_Name = "John Smith",
                            Biography = "John Smith is a prolific fantasy writer known for his richly imagined worlds, complex characters, and epic narratives that captivate readers of all ages. His ability to blend elements of magic and adventure has made him a favorite among fantasy enthusiasts worldwide.",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2532),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2532),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 4,
                            Author_Name = "Sarah Johnson",
                            Biography = "Sarah Johnson writes poignant historical fiction that vividly portrays the past through meticulously researched details and emotionally resonant storytelling. Her novels transport readers to different eras, offering insights into human nature and societal change.,",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2600),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2601),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 5,
                            Author_Name = "Michael Andrews",
                            Biography = "Michael Andrews explores the intersection of science, technology, and humanity in his thought-provoking science fiction works. Known for his innovative ideas and compelling narratives, Andrews pushes the boundaries of imagination while addressing profound questions about the future.",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2603),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2603),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 6,
                            Author_Name = "Emily Chen",
                            Biography = "Emily Chens thrillers are known for their gripping plots, complex characters, and unpredictable twists that keep readers on the edge of their seats until the final page. Her ability to create suspenseful narratives filled with psychological depth has garnered critical acclaim in the thriller genre.",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2605),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2605),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 7,
                            Author_Name = "David Rodriguez",
                            Biography = "David Rodriguez's novels delve into philosophical themes with lyrical prose and introspective storytelling that challenges readers to contemplate life's complexities. His explorations of human emotions and existential questions resonate deeply, making his literary fiction a compelling read for those seeking profound insights.",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2607),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2607),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 8,
                            Author_Name = "Alice Thompson",
                            Biography = "Alice Thompson writes enchanting tales of magic and adventure that transport readers to fantastical realms filled with wonder and danger. Her ability to weave intricate plots and create vivid settings has earned her a dedicated following among fans of fantasy literature",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2609),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2609),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 9,
                            Author_Name = "Mark Davis",
                            Biography = "Mark Davis is a master of suspense and thriller, crafting stories that blend heart-pounding action with intricate plot twists. His ability to create tension and suspenseful atmospheres has made him a favorite among readers who enjoy thrillers that keep them guessing until the very end.",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2611),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2612),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 10,
                            Author_Name = "Sophie White",
                            Biography = "Sophie White's historical novels bring to life forgotten tales from the past, illuminating lesser-known events and characters with compassion and historical accuracy. Her meticulous research and evocative prose make her novels a captivating journey into different epochs",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2613),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2614),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 11,
                            Author_Name = "Thomas Brown",
                            Biography = "Thomas Brown's science fiction explores complex themes of identity, technology, and the nature of reality with a blend of intellectual rigor and imaginative storytelling. His speculative visions of future societies and technological advancements provoke thought and reflection",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2615),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2615),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 12,
                            Author_Name = "Emma Wilson",
                            Biography = "Emma Wilson's stories are filled with hope and resilience, portraying characters who face adversity with courage and grace. Her uplifting narratives and heartfelt storytelling resonate with readers seeking stories of human strength and the power of optimism.",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2617),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2617),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 13,
                            Author_Name = "Matthew Lee",
                            Biography = "Matthew Lee's horror novels keep readers on the edge of their seats with chilling suspense, supernatural phenomena, and spine-tingling plot twists. His atmospheric settings and vivid descriptions create an immersive reading experience for fans of horror and suspense fiction.",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2619),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2619),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 14,
                            Author_Name = "Olivia Green",
                            Biography = "Olivia Green writes gripping mysteries set in exotic locations, blending suspenseful plots with rich cultural details and compelling characters. Her ability to create atmospheric settings and intricate puzzles has earned her a reputation as a master of the mystery genre.",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2621),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2621),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 15,
                            Author_Name = "Daniel Moore",
                            Biography = "Daniel Moore's novels blend adventure with profound explorations of human nature and the mysteries of existence. His gripping narratives and multifaceted characters take readers on thrilling journeys that delve into the depths of the human psyche.",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2622),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2623),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 16,
                            Author_Name = "Lucy Hall",
                            Biography = "Lucy Hall's fantasy worlds are intricate and imaginative, filled with magic, mythical creatures, and quests that challenge characters to discover their true strengths. Her ability to create enchanting realms and compelling characters makes her a beloved author in the fantasy genre.",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2625),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2625),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 17,
                            Author_Name = "James Taylor",
                            Biography = "James Taylor's historical fiction transports readers to pivotal moments in history, weaving together personal stories with larger historical events to create a vivid tapestry of the past. His meticulous attention to historical detail and evocative storytelling bring history to life for readers.",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2627),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2627),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Author_Id = 18,
                            Author_Name = "Sophia Clark",
                            Biography = "Sophia Clark explores the mysteries of quantum physics and the implications of scientific discovery on humanity's understanding of reality.Her speculative fiction challenges readers to ponder the philosophical and ethical implications of technological advancements.",
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2629),
                            Created_By = "admin",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2629),
                            Updated_By = "admin"
                        });
                });

            modelBuilder.Entity("Bookstore.Entities.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Author_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genre_Id")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("Publication_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Author_Id");

                    b.HasIndex("Genre_Id");

                    b.HasIndex("Title", "Publication_Date")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author_Id = 1,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2217),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 2,
                            Price = 649.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1888),
                            Title = "A Little Princess",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2225),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Author_Id = 2,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2232),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 6,
                            Price = 150.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1992),
                            Title = "Ratan Tata - A Complete Biography",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2233),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 3,
                            Author_Id = 3,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2235),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 2,
                            Price = 750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2003),
                            Title = "The Hidden Realm",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2236),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 4,
                            Author_Id = 4,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2238),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 3,
                            Price = 1750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1983),
                            Title = "Echoes of Yesterday",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2239),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 5,
                            Author_Id = 5,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2241),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 5,
                            Price = 1750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2012),
                            Title = "Quantum Leap",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2241),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 6,
                            Author_Id = 6,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2243),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 1,
                            Price = 1750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1997),
                            Title = "Shadows in the Mist",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2243),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 7,
                            Author_Id = 7,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2245),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 2,
                            Price = 1750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2009),
                            Title = "Beyond the Horizon",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2246),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 8,
                            Author_Id = 8,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2248),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 2,
                            Price = 1750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2017),
                            Title = "Whispers in the Wind",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2249),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 9,
                            Author_Id = 9,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2251),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 1,
                            Price = 1750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1999),
                            Title = "The Last Stand",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2252),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 10,
                            Author_Id = 10,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2255),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 3,
                            Price = 1750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1982),
                            Title = "The Forgotten Key",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2255),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 11,
                            Author_Id = 11,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2257),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 5,
                            Price = 1750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2015),
                            Title = "Infinite Worlds",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2258),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 12,
                            Author_Id = 12,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2260),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 11,
                            Price = 1750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1997),
                            Title = "A Glimmer of Hope",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2260),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 13,
                            Author_Id = 13,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2262),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 4,
                            Price = 1750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1985),
                            Title = "Darkness Falls",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2262),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 14,
                            Author_Id = 14,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2264),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 1,
                            Price = 1750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2001),
                            Title = "The Golden Hour",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2265),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 15,
                            Author_Id = 15,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2267),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 2,
                            Price = 1750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2003),
                            Title = "Into the Abyss",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2267),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 16,
                            Author_Id = 16,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2269),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 2,
                            Price = 1750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2008),
                            Title = "Through the Looking Glass",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2270),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 17,
                            Author_Id = 17,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2272),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 3,
                            Price = 1750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1999),
                            Title = "The Sands of Time",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2272),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Id = 18,
                            Author_Id = 18,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2274),
                            Created_By = "admin",
                            Description = "xyz",
                            Genre_Id = 5,
                            Price = 1750.0,
                            Publication_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1998),
                            Title = "The Quantum Paradox",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2275),
                            Updated_By = "admin"
                        });
                });

            modelBuilder.Entity("Bookstore.Entities.Genres", b =>
                {
                    b.Property<int>("Genre_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Genre_Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Genre_Id");

                    b.HasIndex("Genre_Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Genre_Id = 1,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2678),
                            Created_By = "admin",
                            Genre_Name = "Thriller",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2680),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Genre_Id = 2,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2684),
                            Created_By = "admin",
                            Genre_Name = "Fantasy",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2685),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Genre_Id = 3,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2686),
                            Created_By = "admin",
                            Genre_Name = "History",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2687),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Genre_Id = 4,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2688),
                            Created_By = "admin",
                            Genre_Name = "Horror",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2688),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Genre_Id = 5,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2690),
                            Created_By = "admin",
                            Genre_Name = "Science Fiction",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2690),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Genre_Id = 6,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2692),
                            Created_By = "admin",
                            Genre_Name = "Biography",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2692),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Genre_Id = 7,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2694),
                            Created_By = "admin",
                            Genre_Name = "Self-Help",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2694),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Genre_Id = 8,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2695),
                            Created_By = "admin",
                            Genre_Name = "Spirituality",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2696),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Genre_Id = 9,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2697),
                            Created_By = "admin",
                            Genre_Name = "Politics",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2698),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Genre_Id = 10,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2699),
                            Created_By = "admin",
                            Genre_Name = "Law",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2700),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Genre_Id = 11,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2701),
                            Created_By = "admin",
                            Genre_Name = "Literacy",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2701),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Genre_Id = 12,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2703),
                            Created_By = "admin",
                            Genre_Name = "Travel and Tourism",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2703),
                            Updated_By = "admin"
                        },
                        new
                        {
                            Genre_Id = 13,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2704),
                            Created_By = "admin",
                            Genre_Name = "Sports",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2705),
                            Updated_By = "admin"
                        });
                });

            modelBuilder.Entity("Bookstore.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updated_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2755),
                            Created_By = "admin",
                            Email = "Pavikannan@gmail.com",
                            FirstName = "Pavithra",
                            LastName = "G",
                            Password = "Pass@123",
                            Updated_At = new DateTime(2024, 8, 3, 14, 1, 31, 400, DateTimeKind.Utc).AddTicks(2756),
                            Updated_By = "admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Bookstore.Entities.Books", b =>
                {
                    b.HasOne("Bookstore.Entities.Authors", "author")
                        .WithMany("Books")
                        .HasForeignKey("Author_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore.Entities.Genres", "genre")
                        .WithMany("Books")
                        .HasForeignKey("Genre_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("author");

                    b.Navigation("genre");
                });

            modelBuilder.Entity("Bookstore.Entities.Authors", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Bookstore.Entities.Genres", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
